# Generated by Django 3.2.4 on 2021-09-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('faceId', models.AutoField(primary_key=True, serialize=False)),
                ('faceImg', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
